### ISSUE TITLE
TPS annotations  

### ISSUE THREAD

**Issue by ajshedivy** [ajshedivy/tps#13]
So far I have been able to run the EGFR utility functions to produce the annotations, yet I am still running into issues that I have experienced in the past with https://github.com/ajshedivy/tps/issues/9#issuecomment-627725410 
namely, a 500 error. 

What was the procedure used when creating the node annotations for the manuscript? I want to see if I can manually import the annotations file in order to get a better idea as to how to automate the process. When I import the file via `file > import > Table from file` (in Cytoscape), the file is successfully loaded but I believe the types of the columns are not imported correctly. This is a feature that you can manually set as well as automate using py2cytoscape.

**Comment by ajshedivy** [comment]
Here is the code used within a Jupyter notebook that causes an error

```python
# create cyrest client
cyy = cyrest.cyclient()

# Step 1: Create py2cytoscape client
cy = CyRestClient()

# Reset
cy.session.delete()

# Step 2: Load network from somewhere
cy.network.create_from(output)

# Step 3: Apply layout
# list of styles to apply
# only contains the one style loaded from style file
style = cyy.vizmap.load_file(style)
cyy.vizmap.apply(style[0])
cyy.table.import_file(annotations)
```

Error:
(last line above)

```python
ValueError: {'status': 500, 'message': 'java.lang.NullPointerException', 
'type': 'urn:cytoscape:ci:cyrest-core:v1:handle-json-command:errors:2', 
'link': 'file:/C:/Users/ajshe/CytoscapeConfiguration/3/framework-cytoscape.log'}
```

**Comment by agitter** [comment]
We looked at the `egf_tps_pathway.cys` example for the TPS manuscript.  Cross-referencing that with the [style file template](https://github.com/ajshedivy/tps/blob/visualization_v2/notebooks/tps_style_template.xml) we can see which custom graphics are used:
- NODE_CUSTOMGRAPHICS_1 is a line graph for the significantly changing phosphosites
- NODE_CUSTOMGRAPHICS_2 is a line graph for the insignificant phosphosites
- NODE_CUSTOMGRAPHICS_3 is the heat map used to show the TPS activity windows (white, gray, blue, red) below the line graphs

**Comment by ajshedivy** [comment]
I have successfully implemented loading the annotations for significant phosphosites. I have linked the Cytoscape session file on my branch https://github.com/ajshedivy/tps/tree/visualization_v2/sessions/test

I am able to visualize both significant and insignificant phosphosites out of the box but I am still having some issues rendering the heat maps correctly. As we discussed, this may be due to the way Cytoscape orders graphics.

**Comment by agitter** [comment]
There are some open problems with the activity state annotations that are used for the heat map graphics.  Because those heat maps are not all that important, we decided to focus the line graphs for significant and insignificant peptides for the first pull request.
