### ISSUE TITLE
Explore absolute or relative style file paths

### ISSUE THREAD

**Issue by agitter** [ajshedivy/tps#3]
A relative path to a style file may be interpreted as relative to the Cytoscape directory, not the working directory.  We can use Python to convert the relative path to an absolute path.

**Comment by ajshedivy** [comment]
I have started a new exploratory branch called `visualization_v2` that I will use to make further changes to from the first pull request. So far I have added converting relative paths to absolute paths using `os.path.abspath(path)` which seems to fix the issue we we having when loading style files from locations other than Cytoscapes install directory,

**Comment by agitter** [comment]
That's great.  I'm glad you found the `os.path.abspath`.  That is what I would have recommended.
