### ISSUE TITLE
Decide on search behavior for Cytoscape executable

### ISSUE THREAD

**Issue by agitter** [ajshedivy/tps#4]
We do see a use case for providing a path to Cytoscape and launching it automatically.  That will be useful when running inside Docker.

We discussed other options in https://github.com/gitter-lab/tps/pull/2#discussion_r380259156

The Cytoscape directory can become an optional argument https://github.com/gitter-lab/tps/pull/2#discussion_r397236054

**Comment by ajshedivy** [comment]
I've done some exploratory work with this, and I have a python file called `find_Cytoscape.py` that I am using to test out different search algorithms and techniques. This file is in my `visualization_v2` branch

**Comment by ajshedivy** [comment]
Right now I am looking into running multiple searches in "parallel" and checking to see which function returns first. I am still looking for a way to communicate the return values of multiple functions and how to control execution

**Comment by agitter** [comment]
Which paths do you search in parallel?  Is the idea that we would have a pre-compiled list of common install locations and try to search those if the user doesn't provide a directory as a command line argument?

In the interest of building up functionality slowly, we could save the list of common install directories for a later update.  The core functionality would be to:
- Accept an optional single path to the Cytoscape executable the user wants to use as a command line argument
- Check if Cytoscape is already running; if yes, use that session to load the TPS network
- If Cytoscape is not already running and a path was provided, attempt to launch Cytoscape
- If the Cytoscape does not exist on that path, the launch fails, or it takes more than a max number of retries, throw an error and quit
- If Cytoscape was not running and no path was provided, throw an error and quit

**Comment by agitter** [comment]
I still recommend getting the single-threaded version working well first, but I also looked into options for the parallel search.  There is support for [sharing state](https://docs.python.org/3.6/library/multiprocessing.html#sharing-state-between-processes) between processes with shared memory.  Sharing a boolean value that starts as False and is set to True whenever one parallel search finds the executable could be a valid strategy.  If each process only reads the value or sets it to True, I don't see obvious concurrency issues that could arise.  However, debugging and testing parallel programs is very tricky, and there could be behaviors I'm not aware of.
