### ISSUE TITLE
Additional Features

### ISSUE THREAD

**Issue by ajshedivy** [ajshedivy/tps#9]
As development continues, we can start adding more py2cytoscape optional commands such as annotations, and session commands

**Comment by ajshedivy** [comment]
5/12/2020

I began looking at the jupyter notebooks that are used to create the annotations for the TPS manuscript. I believe that we can tweak the utility notebooks slightly such that they are formatted in a way that agrees with py2cytoscape. We want to specifically look at https://py2cytoscape.readthedocs.io/en/latest/cyrest/table/#cyclienttableimport_file 
for importing annotations.

**Comment by ajshedivy** [comment]
Additional commands can be added in order to export a session file or a pdf. Here is a reference:
https://py2cytoscape.readthedocs.io/en/latest/cyrest/session/#cyclientsessionsave_as

**Comment by agitter** [comment]
Exporting a PDF would a a valuable short term goal.  We could then extend our Cytoscape test code to confirm that a non-empty PDF is written after your script runs.
